### ISSUE TITLE
Yet another unkown state (95 - battery diagnosis)

### ISSUE THREAD

**Issue by yonarw** [mchwalisz/pysenec#10]
Hi,
I get yet another unknown battery state now:
```
  File "cli.py", line 17, in run
    print(f"System state: {senec.system_state}")
  File "[...]/Python/3.8/lib/python/site-packages/pysenec/__init__.py", line 22, in system_state
    return SYSTEM_STATE_NAME[value]
KeyError: 95

```
Display on device shows "Batterydiagnose" (german). Is there a way to find the official state name? Otherwise I'll create a pull request with the  added key value `95 : "BATTERY DIAGNOSIS"`.

**Comment by neubi4** [comment]
Hi,

i think the "official" way is the translation file from senecs webinterface, which is http://senec-ip/js/EN-en.js

Unfortunately it only has the state IDs up to 94 (at leas on my V2.1 with FW 1990), which is why the senec webinterface also can not display this new states. I tried to find a simmilar map at mein-senec.de but could not find one.

So adding `95 : "BATTERY DIAGNOSIS"`  via a pull request is ok in my opinion.
